# Generated by Django 3.1.1 on 2021-03-23 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210320_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_social',
            new_name='is_complete',
        ),
    ]
