# Generated by Django 3.1.1 on 2021-03-18 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=1, max_digits=5)),
                ('color', models.CharField(max_length=25)),
                ('options', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=25)),
                ('state', models.IntegerField(choices=[(0, 'UNAVAILABLE'), (1, 'AVAILABLE')])),
                ('discount', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='account.creator')),
            ],
        ),
        migrations.CreateModel(
            name='ItemReaction',
            fields=[
                ('reaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.reaction')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='item.item')),
            ],
            bases=('common.reaction',),
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.image')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='item.item')),
            ],
            bases=('common.image',),
        ),
        migrations.CreateModel(
            name='ItemComments',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.comment')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='item.item')),
            ],
            bases=('common.comment',),
        ),
    ]
