# Generated by Django 3.1.1 on 2021-03-20 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creator',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='creator',
            new_name='user',
        ),
    ]
