# Generated by Django 3.1.1 on 2021-03-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='reaction_type',
            field=models.IntegerField(choices=[(1, 'LIKE'), (2, 'HEART'), (3, 'BRAVO'), (4, 'AMAZED'), (5, 'DISLIKE')]),
        ),
    ]
